// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUVPJMhAzaVYe5TJkdMugttCTWyxMtebY',
    appId: '1:407588695056:web:2ff0188a61d6476a39ae95',
    messagingSenderId: '407588695056',
    projectId: 'al--flutterauth',
    authDomain: 'al--flutterauth.firebaseapp.com',
    storageBucket: 'al--flutterauth.appspot.com',
    measurementId: 'G-2E72DEQKZF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcDdDHUPqfKUy8Xx60ZqJt8kbLwnAmll4',
    appId: '1:407588695056:android:e9666d34d5e0516739ae95',
    messagingSenderId: '407588695056',
    projectId: 'al--flutterauth',
    storageBucket: 'al--flutterauth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5x5yjOzQjhjrbGhxeFwQiig4MNK3ykH8',
    appId: '1:407588695056:ios:99376b746131e99339ae95',
    messagingSenderId: '407588695056',
    projectId: 'al--flutterauth',
    storageBucket: 'al--flutterauth.appspot.com',
    iosClientId: '407588695056-c37t6h7c7821qu7c3hofrj090pidrf7v.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5x5yjOzQjhjrbGhxeFwQiig4MNK3ykH8',
    appId: '1:407588695056:ios:99376b746131e99339ae95',
    messagingSenderId: '407588695056',
    projectId: 'al--flutterauth',
    storageBucket: 'al--flutterauth.appspot.com',
    iosClientId: '407588695056-c37t6h7c7821qu7c3hofrj090pidrf7v.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFirstApp',
  );
}
